In [258]:
import numpy as np

def step_function(x): # True function
    return np.where(x < 0.35, 0, np.where(x < 0.45, 0.7, np.where(x < 0.55, 1.4, np.where(x < 0.65, 0.7, 0))))

def generate_data(x_points, y_true, noise_variance=0.25):
    noise = np.random.normal(0, np.sqrt(noise_variance), len(x_points))
    y_noisy = y_true + noise
    return y_noisy
    
def create_bootstrap_indices_and_Nbi(n_data_points, n_bootstrap):
    indices_list = np.random.choice(n_data_points, (n_bootstrap, n_data_points), replace=True)
    counts = np.zeros((n_bootstrap, n_data_points), dtype=int)
    for x_i in range(n_data_points):
        counts[:, x_i] = np.sum(indices_list == x_i, axis=1) 
    return indices_list, counts 

In [259]:
def bagging_decision_trees(x_points, y_noisy, n_bootstrap  ):
    
    n_data_points = x_points.shape[0]
    tree_predictions_b = np.zeros((n_bootstrap, n_data_points))
    indices_list, N_bi = create_bootstrap_indices_and_Nbi(n_data_points=n_data_points, n_bootstrap=n_bootstrap)

    for b in range(n_bootstrap):
        tree_model = DecisionTreeRegressor(max_leaf_nodes=5)
        indices = indices_list[b]
        tree_model.fit(x_points[indices].reshape(-1, 1), y_noisy[indices])
        tree_predictions_b[b, :] = tree_model.predict(x_points.reshape(-1, 1))
        
    return tree_predictions_b, indices_list, N_bi

In [260]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeRegressor

def main():
    
#data for this simulation was drawn from 
#a model y_i = f(x_i) + ε_i, where xi ~ U([0, 1]), ε_i ~ N (0, 1/4), 
#and f(x) is the step function

    # Simulation parameters
    n_data_points = 500
    n_simulations = 1_00  
    n_bootstrap = 10_0  
    seed = 42
    np.random.seed(seed)
    
    # Generate data
    x_points = np.linspace(0, 1, n_data_points)
    y_true = step_function(x_points)
    
    # Array to store the predictions from each simulation
    bagged_predictions = np.zeros((n_simulations, n_data_points))
    
    for s in range(n_simulations):
        
        y_noisy = generate_data(x_points, y_true, noise_variance=0.25)
        
        # Bagging 
        tree_predictions_b, indices_list, N_bi = bagging_decision_trees(x_points, y_noisy, n_bootstrap)
        
        # Average predictions across bootstrap samples
        bagged_predictions[s, :] = tree_predictions.mean(axis=0)

    # Calculate true variance of bagged predictions
    true_variances = bagged_predictions.var(axis=0,ddof=1)
    print(np.mean(true_variances))
    
main()
    

ValueError: could not broadcast input array from shape (3,) into shape (500,)

In [ ]:
def simulation(n_simulations=1000, n_data_points=100, n_bootstrap=1000):
    
    generate_data


def bagging():
    

    # Bagging and prediction
    tree_model = DecisionTreeRegressor(max_leaf_nodes=5)
    tree_predictions = np.zeros((n_bootstrap, n_data_points))
    
    indices_list, N_bi = create_bootstrap_indices_and__Nbi(n_data_points=n_data_points, n_bootstrap=n_bootstrap)

    
    for b in range(n_bootstrap):
        indices = indices_list[b]
        tree_model.fit(x_points[indices].reshape(-1, 1), y_noisy[indices])
        tree_predictions[b, :] = tree_model.predict(x_points.reshape(-1, 1))
        
        

    
    # Average predictions across bootstrap samples
    bagged_predictions[i, :] = tree_predictions.mean(axis=0)

In [ ]:


def emperical_covariance(tree_predictions):
    n_bootstrap = tree_predictions.shape[0]
    n_data_points = tree_predictions.shape[1]
    
    for i in range(1):
    
        sum2 = 0
        for b in range(n_bootstrap):
            sum2 += (N_bi[b,i]-1)*(tree_predictions[b,i]-np.mean(tree_predictions[:,i]))**2
            
    return sum2

            
emperical_covariance(tree_predictions)
    

    

In [230]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeRegressor

''' data for this simulation was drawn from 
a model y_i = f(x_i) + ε_i, where xi ~ U([0, 1]), ε_i ~ N (0, 1/4), 
and f(x) is the step function'''


# Simulation parameters
np.random.seed(42)
n_data_points = 3
n_simulations = 200  # Number of different datasets to simulate
n_bootstrap = 5  # Number of bootstrap samples for bagging
x_points = np.linspace(0, 1, n_data_points)
y_true = step_function(x_points)

# Array to store the predictions from each simulation
bagged_predictions = np.zeros((n_simulations, n_data_points))

# Generate multiple simulated datasets and perform predictions
for i in range(n_simulations):
    
    x_points = np.linspace(0, 1, n_data_points)
    
    
    y_noisy, ytrue = generate_data(x_points)
    noise = np.random.normal(0, np.sqrt(0.25), n_data_points)
    y_noisy = y_true + noise

    # Bagging and prediction
    tree_model = DecisionTreeRegressor(max_leaf_nodes=5)
    tree_predictions = np.zeros((n_bootstrap, n_data_points))
    
    indices_list, N_bi = create_bootstrap_indices_and__Nbi(n_data_points=n_data_points, n_bootstrap=n_bootstrap)

    
    for b in range(n_bootstrap):
        indices = indices_list[b]
        tree_model.fit(x_points[indices].reshape(-1, 1), y_noisy[indices])
        tree_predictions[b, :] = tree_model.predict(x_points.reshape(-1, 1))
        
        

    
    # Average predictions across bootstrap samples
    bagged_predictions[i, :] = tree_predictions.mean(axis=0)

# Calculate true variance of bagged predictions
true_variances = bagged_predictions.var(axis=0)
print(np.mean(true_variances))




0.2289380644696534


In [204]:
import numpy as np

np.random.seed(42)
def count_xi_in_bootstrap_samples(n_data_points, n_bootstrap):
    # Generate random indices for bootstrap samples
    indices_list = np.random.choice(n_data_points, (n_bootstrap, n_data_points), replace=True)
    
    # Initialize a matrix to hold counts of each x_i in each bootstrap sample
    # Transpose to make each column a bootstrap sample for easier list conversion later
    counts = np.zeros((n_bootstrap, n_data_points), dtype=int)

    # Count occurrences of each x_i in the bootstrap samples
    for x_i in range(n_data_points):
        # Counting occurrences for x_i across all bootstrap samples
        counts[:, x_i] = np.sum(indices_list == x_i, axis=1)  # sum across the columns of indices_list


    return indices_list, counts  # Return the indices list and the counts as a list of lists

# Example usage
n_data_points = 3
n_bootstrap = 5
indices_list, counts = count_xi_in_bootstrap_samples(n_data_points, n_bootstrap)

print("Indices List:")
print(indices_list)
print("\nCounts of each x_i for each bootstrap (as list of lists):")
for index, bootstrap_counts in enumerate(counts_list):
    print(f"Bootstrap {index + 1}: {bootstrap_counts}")
    
print(counts)


Indices List:
[[2 0 2]
 [2 0 0]
 [2 1 2]
 [2 2 2]
 [0 2 1]]

Counts of each x_i for each bootstrap (as list of lists):
Bootstrap 1: [1 0 2]
Bootstrap 2: [2 0 1]
Bootstrap 3: [0 1 2]
Bootstrap 4: [0 0 3]
Bootstrap 5: [1 1 1]
[[1 0 2]
 [2 0 1]
 [0 1 2]
 [0 0 3]
 [1 1 1]]


In [ ]:
# Plotting the results
plt.figure(figsize=(10, 6))
plt.plot(x_points, true_variances, label='True Variance of Bagged Predictions')
plt.title('True Variance of Bagged Predictions Across Simulated Datasets')
plt.xlabel('x')
plt.ylabel('Variance')
plt.legend()
plt.show()

